name: CARE Group
url: https://care.hw.ac.uk/

exclude: [bibble, README.md, Makefile, screenshot.png]

description:
  The Cognitive Assistive Robotic Environments (CARE) Group at Heriot-Watt University, part of the Edinburgh Centre for Robotics and the National Robotarium, focuses on enabling robotic, autonomous and interactive systems (RAIS) to provide user-centred assisted living support.

# colorize code snippets with the pygments module
highlighter: pygments

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# allow future posts
future: true

# Sections on the "people" page.
roles:
  - key: faculty
    name: Academic Faculty
  - key: grad
    name: Doctoral Students
  - key: msc
    name: Master's Students
  - key: collab
    name: Collaborators
  - key: alum
    name: Alumni
  - key: research-assistant
    name: Research Assistants
  - key: research-associate
    name: Research Associates
  - key: intern
    name: Interns
  - key: ktp-associate
    name: KTP Associates
  # - key: postdoc
  #   name: Postdoctoral Researchers
  # - key: ugrad
  #   name: Undergraduate Students

# Number of news stories on the front page.
front_page_news: 8

# Number of events on the front page.
font_page_events: 3

# Base pathname for links.
base: ''

# make pages for the _projects folder
collections:
  projects:
    output: true
  past-projects:
    output: true

# Navigation bar links.
navigation:
#  - title: Home
#    link: /
  - title: People
    link: /people.html
  - title: Research
    link: /research.html
  - title: Publications
    link: /publications.html
  - title: Testbeds
    link: /testbeds.html
  - title: Events
    link: /events.html
  - title: Vacancies
    link: /vacancies.html
  - title: Outreach
    link: /outreach.html

# Google Analytics
google_analytics: G-P2QM29HGLX

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

# Social
social:
    name: CARE Group
    links:
      - https://twitter.com/CAREGroupHWU
      - https://github.com/care-group